"feature":
  - head-branch:
    - "feature/*"
    - "*/feature/*"

"bug":
  - head-branch:
    - "fix/*"
    - "*/fix/*"
    - "bug/*"
    - "*/bug/*"

"chore":
  - head-branch:
    - "chore/*"
    - "*/chore/*"