package cl.emilym.sinatra.ui.presentation.theme.trans
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8D4959)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9DF)
val onPrimaryContainerLight = Color(0xFF3A0718)
val secondaryLight = Color(0xFF106681)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBCE9FF)
val onSecondaryContainerLight = Color(0xFF001F2A)
val tertiaryLight = Color(0xFF7A5732)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCBC)
val onTertiaryContainerLight = Color(0xFF2C1600)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF22191B)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF22191B)
val surfaceVariantLight = Color(0xFFF3DDE0)
val onSurfaceVariantLight = Color(0xFF524345)
val outlineLight = Color(0xFF847375)
val outlineVariantLight = Color(0xFFD6C2C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E2F)
val inverseOnSurfaceLight = Color(0xFFFEEDEE)
val inversePrimaryLight = Color(0xFFFFB1C1)
val surfaceDimLight = Color(0xFFE7D6D8)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F1)
val surfaceContainerLight = Color(0xFFFBEAEB)
val surfaceContainerHighLight = Color(0xFFF5E4E6)
val surfaceContainerHighestLight = Color(0xFFEFDEE0)

val primaryDark = Color(0xFFFFB1C1)
val onPrimaryDark = Color(0xFF551D2C)
val primaryContainerDark = Color(0xFF713342)
val onPrimaryContainerDark = Color(0xFFFFD9DF)
val secondaryDark = Color(0xFF8AD0EF)
val onSecondaryDark = Color(0xFF003546)
val secondaryContainerDark = Color(0xFF004D63)
val onSecondaryContainerDark = Color(0xFFBCE9FF)
val tertiaryDark = Color(0xFFECBE91)
val onTertiaryDark = Color(0xFF462A09)
val tertiaryContainerDark = Color(0xFF60401D)
val onTertiaryContainerDark = Color(0xFFFFDCBC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191113)
val onBackgroundDark = Color(0xFFEFDEE0)
val surfaceDark = Color(0xFF191113)
val onSurfaceDark = Color(0xFFEFDEE0)
val surfaceVariantDark = Color(0xFF524345)
val onSurfaceVariantDark = Color(0xFFD6C2C4)
val outlineDark = Color(0xFF9F8C8F)
val outlineVariantDark = Color(0xFF524345)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDEE0)
val inverseOnSurfaceDark = Color(0xFF382E2F)
val inversePrimaryDark = Color(0xFF8D4959)
val surfaceDimDark = Color(0xFF191113)
val surfaceBrightDark = Color(0xFF413738)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191B)
val surfaceContainerDark = Color(0xFF261D1F)
val surfaceContainerHighDark = Color(0xFF312829)
val surfaceContainerHighestDark = Color(0xFF3C3234)







