name: Lint
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
    - release/**
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - androidApp
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |-
        printf "MAPS_API_KEY=${MAPS_API_KEY}" >> secrets.properties
        printf "${GOOGLE_SERVICES_JSON}" >> androidApp/google-services.json
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Lint with Gradle
      env: {}
      run: ./gradlew ${{ matrix.module }}:lintVitalRelease
