name: Label Pull Requests
'on':
  pull_request_target:
    types:
    - edited
    - opened
    - reopened
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
